services:
  backgammon:
    build: .
    container_name: backgammon
    environment:
      - DISPLAY=:99
      - REDIS_HOST=redis
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"